#include<stdio.h>
#include<string.h>

int main()
{
    char nancyj[63][8][20];
    FILE *p_file;
    p_file=fopen("block.data","wb");
    strcpy(nancyj[0][0],"         ");
    strcpy(nancyj[0][1],"         ");
    strcpy(nancyj[0][2],"  _|_|_| ");
    strcpy(nancyj[0][3],"_|    _| ");
    strcpy(nancyj[0][4],"_|    _| ");
    strcpy(nancyj[0][5],"  _|_|_| ");
    strcpy(nancyj[0][6],"         ");
    strcpy(nancyj[0][7],"         ");
    strcpy(nancyj[1][0],"         ");
    strcpy(nancyj[1][1],"_|       ");
    strcpy(nancyj[1][2],"_|_|_|   ");
    strcpy(nancyj[1][3],"_|    _| ");
    strcpy(nancyj[1][4],"_|    _| ");
    strcpy(nancyj[1][5],"_|_|_|   ");
    strcpy(nancyj[1][6],"         ");
    strcpy(nancyj[1][7],"         ");
    strcpy(nancyj[2][0],"         ");
    strcpy(nancyj[2][1],"         ");
    strcpy(nancyj[2][2],"  _|_|_| ");
    strcpy(nancyj[2][3],"_|       ");
    strcpy(nancyj[2][4],"_|       ");
    strcpy(nancyj[2][5],"  _|_|_| ");
    strcpy(nancyj[2][6],"         ");
    strcpy(nancyj[2][7],"         ");
    strcpy(nancyj[3][0],"         ");
    strcpy(nancyj[3][1],"      _| ");
    strcpy(nancyj[3][2],"  _|_|_| ");
    strcpy(nancyj[3][3],"_|    _| ");
    strcpy(nancyj[3][4],"_|    _| ");
    strcpy(nancyj[3][5],"  _|_|_| ");
    strcpy(nancyj[3][6],"         ");
    strcpy(nancyj[3][7],"         ");
    strcpy(nancyj[4][0],"         ");
    strcpy(nancyj[4][1],"         ");
    strcpy(nancyj[4][2],"  _|_|   ");
    strcpy(nancyj[4][3],"_|_|_|_| ");
    strcpy(nancyj[4][4],"_|       ");
    strcpy(nancyj[4][5],"  _|_|_| ");
    strcpy(nancyj[4][6],"         ");
    strcpy(nancyj[4][7],"         ");
    strcpy(nancyj[5][0],"         ");
    strcpy(nancyj[5][1],"    _|_| ");
    strcpy(nancyj[5][2],"  _|     ");
    strcpy(nancyj[5][3],"_|_|_|_| ");
    strcpy(nancyj[5][4],"  _|     ");
    strcpy(nancyj[5][5],"  _|     ");
    strcpy(nancyj[5][6],"         ");
    strcpy(nancyj[5][7],"         ");
    strcpy(nancyj[6][0],"         ");
    strcpy(nancyj[6][1],"         ");
    strcpy(nancyj[6][2],"  _|_|_| ");
    strcpy(nancyj[6][3],"_|    _| ");
    strcpy(nancyj[6][4],"_|    _| ");
    strcpy(nancyj[6][5],"  _|_|_| ");
    strcpy(nancyj[6][6],"      _| ");
    strcpy(nancyj[6][7],"  _|_|   ");
    strcpy(nancyj[7][0],"         ");
    strcpy(nancyj[7][1],"_|       ");
    strcpy(nancyj[7][2],"_|_|_|   ");
    strcpy(nancyj[7][3],"_|    _| ");
    strcpy(nancyj[7][4],"_|    _| ");
    strcpy(nancyj[7][5],"_|    _| ");
    strcpy(nancyj[7][6],"         ");
    strcpy(nancyj[7][7],"         ");
    strcpy(nancyj[8][0],"    ");
    strcpy(nancyj[8][1]," _| ");
    strcpy(nancyj[8][2],"    ");
    strcpy(nancyj[8][3]," _| ");
    strcpy(nancyj[8][4]," _| ");
    strcpy(nancyj[8][5]," _| ");
    strcpy(nancyj[8][6],"    ");
    strcpy(nancyj[8][7],"    ");
    strcpy(nancyj[9][0],"    ");
    strcpy(nancyj[9][1],"  _| ");
    strcpy(nancyj[9][2],"     ");
    strcpy(nancyj[9][3],"  _| ");
    strcpy(nancyj[9][4],"  _| ");
    strcpy(nancyj[9][5],"  _| ");
    strcpy(nancyj[9][6],"  _| ");
    strcpy(nancyj[9][7],"_|   ");
    strcpy(nancyj[10][0],"        ");
    strcpy(nancyj[10][1],"_|      ");
    strcpy(nancyj[10][2],"_|  _|  ");
    strcpy(nancyj[10][3],"_|_|    ");
    strcpy(nancyj[10][4],"_|  _|  ");
    strcpy(nancyj[10][5],"_|    _|");
    strcpy(nancyj[10][6],"        ");
    strcpy(nancyj[10][7],"        ");
    strcpy(nancyj[11][0],"    ");
    strcpy(nancyj[11][1]," _| ");
    strcpy(nancyj[11][2]," _| ");
    strcpy(nancyj[11][3]," _| ");
    strcpy(nancyj[11][4]," _| ");
    strcpy(nancyj[11][5]," _| ");
    strcpy(nancyj[11][6],"    ");
    strcpy(nancyj[11][7],"    ");
    strcpy(nancyj[12][0],"               ");
    strcpy(nancyj[12][1],"               ");
    strcpy(nancyj[12][2],"_|_|_|  _|_|   ");
    strcpy(nancyj[12][3],"_|    _|    _| ");
    strcpy(nancyj[12][4],"_|    _|    _| ");
    strcpy(nancyj[12][5],"_|    _|    _| ");
    strcpy(nancyj[12][6],"               ");
    strcpy(nancyj[12][7],"               ");
    strcpy(nancyj[13][0],"         ");
    strcpy(nancyj[13][1],"         ");
    strcpy(nancyj[13][2],"_|_|_|   ");
    strcpy(nancyj[13][3],"_|    _| ");
    strcpy(nancyj[13][4],"_|    _| ");
    strcpy(nancyj[13][5],"_|    _| ");
    strcpy(nancyj[13][6],"         ");
    strcpy(nancyj[13][7],"         ");
    strcpy(nancyj[14][0],"         ");
    strcpy(nancyj[14][1],"         ");
    strcpy(nancyj[14][2],"  _|_|   ");
    strcpy(nancyj[14][3],"_|    _| ");
    strcpy(nancyj[14][4],"_|    _| ");
    strcpy(nancyj[14][5],"  _|_|   ");
    strcpy(nancyj[14][6],"         ");
    strcpy(nancyj[14][7],"         ");
    strcpy(nancyj[15][0],"         ");
    strcpy(nancyj[15][1],"         ");
    strcpy(nancyj[15][2],"_|_|_|   ");
    strcpy(nancyj[15][3],"_|    _| ");
    strcpy(nancyj[15][4],"_|    _| ");
    strcpy(nancyj[15][5],"_|_|_|   ");
    strcpy(nancyj[15][6],"_|       ");
    strcpy(nancyj[15][7],"_|       ");
    strcpy(nancyj[16][0],"         ");
    strcpy(nancyj[16][1],"         ");
    strcpy(nancyj[16][2],"  _|_|_| ");
    strcpy(nancyj[16][3],"_|    _| ");
    strcpy(nancyj[16][4],"_|    _| ");
    strcpy(nancyj[16][5],"  _|_|_| ");
    strcpy(nancyj[16][6],"      _| ");
    strcpy(nancyj[16][7],"      _| ");
    strcpy(nancyj[17][0],"         ");
    strcpy(nancyj[17][1],"         ");
    strcpy(nancyj[17][2],"_|  _|_| ");
    strcpy(nancyj[17][3],"_|_|     ");
    strcpy(nancyj[17][4],"_|       ");
    strcpy(nancyj[17][5],"_|       ");
    strcpy(nancyj[17][6],"         ");
    strcpy(nancyj[17][7],"         ");
    strcpy(nancyj[18][0],"         ");
    strcpy(nancyj[18][1],"         ");
    strcpy(nancyj[18][2],"  _|_|_| ");
    strcpy(nancyj[18][3],"_|_|     ");
    strcpy(nancyj[18][4],"    _|_| ");
    strcpy(nancyj[18][5],"_|_|_|   ");
    strcpy(nancyj[18][6],"         ");
    strcpy(nancyj[18][7],"         ");
    strcpy(nancyj[19][0],"         ");
    strcpy(nancyj[19][1],"  _|     ");
    strcpy(nancyj[19][2],"_|_|_|_| ");
    strcpy(nancyj[19][3],"  _|     ");
    strcpy(nancyj[19][4],"  _|     ");
    strcpy(nancyj[19][5],"    _|_| ");
    strcpy(nancyj[19][6],"         ");
    strcpy(nancyj[19][7],"         ");
    strcpy(nancyj[20][0],"         ");
    strcpy(nancyj[20][1],"         ");
    strcpy(nancyj[20][2],"_|    _| ");
    strcpy(nancyj[20][3],"_|    _| ");
    strcpy(nancyj[20][4],"_|    _| ");
    strcpy(nancyj[20][5],"  _|_|_| ");
    strcpy(nancyj[20][6],"         ");
    strcpy(nancyj[20][7],"         ");
    strcpy(nancyj[21][0],"           ");
    strcpy(nancyj[21][1],"           ");
    strcpy(nancyj[21][2],"_|      _| ");
    strcpy(nancyj[21][3],"_|      _| ");
    strcpy(nancyj[21][4],"  _|  _|   ");
    strcpy(nancyj[21][5],"    _|     ");
    strcpy(nancyj[21][6],"           ");
    strcpy(nancyj[21][7],"           ");
    strcpy(nancyj[22][0],"                   ");
    strcpy(nancyj[22][1],"                   ");
    strcpy(nancyj[22][2]," _|      _|      _|");
    strcpy(nancyj[22][3]," _|      _|      _|");
    strcpy(nancyj[22][4],"  _|  _|  _|  _|   ");
    strcpy(nancyj[22][5],"    _|      _|     ");
    strcpy(nancyj[22][6],"                   ");
    strcpy(nancyj[22][7],"                   ");
    strcpy(nancyj[23][0],"         ");
    strcpy(nancyj[23][1],"         ");
    strcpy(nancyj[23][2],"_|    _| ");
    strcpy(nancyj[23][3],"  _|_|   ");
    strcpy(nancyj[23][4],"_|    _| ");
    strcpy(nancyj[23][5],"_|    _| ");
    strcpy(nancyj[23][6],"         ");
    strcpy(nancyj[23][7],"         ");
    strcpy(nancyj[24][0],"         ");
    strcpy(nancyj[24][1],"         ");
    strcpy(nancyj[24][2],"_|    _| ");
    strcpy(nancyj[24][3],"_|    _| ");
    strcpy(nancyj[24][4],"_|    _| ");
    strcpy(nancyj[24][5],"  _|_|_| ");
    strcpy(nancyj[24][6],"      _| ");
    strcpy(nancyj[24][7],"  _|_|   ");
    strcpy(nancyj[25][0],"         ");
    strcpy(nancyj[25][1],"         ");
    strcpy(nancyj[25][2],"_|_|_|_| ");
    strcpy(nancyj[25][3],"    _|   ");
    strcpy(nancyj[25][4],"  _|     ");
    strcpy(nancyj[25][5],"_|_|_|_| ");
    strcpy(nancyj[25][6],"         ");
    strcpy(nancyj[25][7],"         ");
    strcpy(nancyj[26][0],"         ");
    strcpy(nancyj[26][1],"  _|_|   ");
    strcpy(nancyj[26][2],"_|    _| ");
    strcpy(nancyj[26][3],"_|_|_|_| ");
    strcpy(nancyj[26][4],"_|    _| ");
    strcpy(nancyj[26][5],"_|    _| ");
    strcpy(nancyj[26][6],"         ");
    strcpy(nancyj[26][7],"         ");
    strcpy(nancyj[27][0],"         ");
    strcpy(nancyj[27][1],"_|_|_|   ");
    strcpy(nancyj[27][2],"_|    _| ");
    strcpy(nancyj[27][3],"_|_|_|   ");
    strcpy(nancyj[27][4],"_|    _| ");
    strcpy(nancyj[27][5],"_|_|_|   ");
    strcpy(nancyj[27][6],"         ");
    strcpy(nancyj[27][7],"         ");
    strcpy(nancyj[28][0],"         ");
    strcpy(nancyj[28][1],"  _|_|_| ");
    strcpy(nancyj[28][2],"_|       ");
    strcpy(nancyj[28][3],"_|       ");
    strcpy(nancyj[28][4],"_|       ");
    strcpy(nancyj[28][5],"  _|_|_| ");
    strcpy(nancyj[28][6],"         ");
    strcpy(nancyj[28][7],"         ");
    strcpy(nancyj[29][0],"         ");
    strcpy(nancyj[29][1],"_|_|_|   ");
    strcpy(nancyj[29][2],"_|    _| ");
    strcpy(nancyj[29][3],"_|    _| ");
    strcpy(nancyj[29][4],"_|    _| ");
    strcpy(nancyj[29][5],"_|_|_|   ");
    strcpy(nancyj[29][6],"         ");
    strcpy(nancyj[29][7],"         ");
    strcpy(nancyj[30][0],"         ");
    strcpy(nancyj[30][1],"_|_|_|_| ");
    strcpy(nancyj[30][2],"_|       ");
    strcpy(nancyj[30][3],"_|_|_|   ");
    strcpy(nancyj[30][4],"_|       ");
    strcpy(nancyj[30][5],"_|_|_|_| ");
    strcpy(nancyj[30][6],"         ");
    strcpy(nancyj[30][7],"         ");
    strcpy(nancyj[31][0],"         ");
    strcpy(nancyj[31][1],"_|_|_|_| ");
    strcpy(nancyj[31][2],"_|       ");
    strcpy(nancyj[31][3],"_|_|_|   ");
    strcpy(nancyj[31][4],"_|       ");
    strcpy(nancyj[31][5],"_|       ");
    strcpy(nancyj[31][6],"         ");
    strcpy(nancyj[31][7],"         ");
    strcpy(nancyj[32][0],"         ");
    strcpy(nancyj[32][1],"  _|_|_| ");
    strcpy(nancyj[32][2],"_|       ");
    strcpy(nancyj[32][3],"_|  _|_| ");
    strcpy(nancyj[32][4],"_|    _| ");
    strcpy(nancyj[32][5],"  _|_|_| ");
    strcpy(nancyj[32][6],"         ");
    strcpy(nancyj[32][7],"         ");
    strcpy(nancyj[33][0],"         ");
    strcpy(nancyj[33][1],"_|    _| ");
    strcpy(nancyj[33][2],"_|    _| ");
    strcpy(nancyj[33][3],"_|_|_|_| ");
    strcpy(nancyj[33][4],"_|    _| ");
    strcpy(nancyj[33][5],"_|    _| ");
    strcpy(nancyj[33][6],"         ");
    strcpy(nancyj[33][7],"         ");
    strcpy(nancyj[34][0],"       ");
    strcpy(nancyj[34][1],"_|_|_| ");
    strcpy(nancyj[34][2],"  _|   ");
    strcpy(nancyj[34][3],"  _|   ");
    strcpy(nancyj[34][4],"  _|   ");
    strcpy(nancyj[34][5],"_|_|_| ");
    strcpy(nancyj[34][6],"       ");
    strcpy(nancyj[34][7],"       ");
    strcpy(nancyj[35][0],"         ");
    strcpy(nancyj[35][1],"      _| ");
    strcpy(nancyj[35][2],"      _| ");
    strcpy(nancyj[35][3],"      _| ");
    strcpy(nancyj[35][4],"_|    _| ");
    strcpy(nancyj[35][5],"  _|_|   ");
    strcpy(nancyj[35][6],"         ");
    strcpy(nancyj[35][7],"         ");
    strcpy(nancyj[36][0],"         ");
    strcpy(nancyj[36][1],"_|    _| ");
    strcpy(nancyj[36][2],"_|  _|   ");
    strcpy(nancyj[36][3],"_|_|     ");
    strcpy(nancyj[36][4],"_|  _|   ");
    strcpy(nancyj[36][5],"_|    _| ");
    strcpy(nancyj[36][6],"         ");
    strcpy(nancyj[36][7],"         ");
    strcpy(nancyj[37][0],"         ");
    strcpy(nancyj[37][1],"_|       ");
    strcpy(nancyj[37][2],"_|       ");
    strcpy(nancyj[37][3],"_|       ");
    strcpy(nancyj[37][4],"_|       ");
    strcpy(nancyj[37][5],"_|_|_|_| ");
    strcpy(nancyj[37][6],"         ");
    strcpy(nancyj[37][7],"         ");
    strcpy(nancyj[38][0],"           ");
    strcpy(nancyj[38][1],"_|      _| ");
    strcpy(nancyj[38][2],"_|_|  _|_| ");
    strcpy(nancyj[38][3],"_|  _|  _| ");
    strcpy(nancyj[38][4],"_|      _| ");
    strcpy(nancyj[38][5],"_|      _| ");
    strcpy(nancyj[38][6],"           ");
    strcpy(nancyj[38][7],"           ");
    strcpy(nancyj[39][0],"           ");
    strcpy(nancyj[39][1],"_|      _| ");
    strcpy(nancyj[39][2],"_|_|    _| ");
    strcpy(nancyj[39][3],"_|  _|  _| ");
    strcpy(nancyj[39][4],"_|    _|_| ");
    strcpy(nancyj[39][5],"_|      _| ");
    strcpy(nancyj[39][6],"           ");
    strcpy(nancyj[39][7],"           ");
    strcpy(nancyj[40][0],"         ");
    strcpy(nancyj[40][1],"  _|_|   ");
    strcpy(nancyj[40][2],"_|    _| ");
    strcpy(nancyj[40][3],"_|    _| ");
    strcpy(nancyj[40][4],"_|    _| ");
    strcpy(nancyj[40][5],"  _|_|   ");
    strcpy(nancyj[40][6],"         ");
    strcpy(nancyj[40][7],"         ");
    strcpy(nancyj[41][0],"         ");
    strcpy(nancyj[41][1],"_|_|_|   ");
    strcpy(nancyj[41][2],"_|    _| ");
    strcpy(nancyj[41][3],"_|_|_|   ");
    strcpy(nancyj[41][4],"_|       ");
    strcpy(nancyj[41][5],"_|       ");
    strcpy(nancyj[41][6],"         ");
    strcpy(nancyj[41][7],"         ");
    strcpy(nancyj[42][0],"          ");
    strcpy(nancyj[42][1],"  _|_|    ");
    strcpy(nancyj[42][2],"_|    _|  ");
    strcpy(nancyj[42][3],"_|  _|_|  ");
    strcpy(nancyj[42][4],"_|    _|  ");
    strcpy(nancyj[42][5],"  _|_|  _|");
    strcpy(nancyj[42][6],"          ");
    strcpy(nancyj[42][7],"          ");
    strcpy(nancyj[43][0],"         ");
    strcpy(nancyj[43][1],"_|_|_|   ");
    strcpy(nancyj[43][2],"_|    _| ");
    strcpy(nancyj[43][3],"_|_|_|   ");
    strcpy(nancyj[43][4],"_|    _| ");
    strcpy(nancyj[43][5],"_|    _| ");
    strcpy(nancyj[43][6],"         ");
    strcpy(nancyj[43][7],"         ");
    strcpy(nancyj[44][0],"         ");
    strcpy(nancyj[44][1],"  _|_|_| ");
    strcpy(nancyj[44][2],"_|       ");
    strcpy(nancyj[44][3],"  _|_|   ");
    strcpy(nancyj[44][4],"      _| ");
    strcpy(nancyj[44][5],"_|_|_|   ");
    strcpy(nancyj[44][6],"         ");
    strcpy(nancyj[44][7],"         ");
    strcpy(nancyj[45][0],"           ");
    strcpy(nancyj[45][1],"_|_|_|_|_| ");
    strcpy(nancyj[45][2],"    _|     ");
    strcpy(nancyj[45][3],"    _|     ");
    strcpy(nancyj[45][4],"    _|     ");
    strcpy(nancyj[45][5],"    _|     ");
    strcpy(nancyj[45][6],"           ");
    strcpy(nancyj[45][7],"           ");
    strcpy(nancyj[46][0],"         ");
    strcpy(nancyj[46][1],"_|    _| ");
    strcpy(nancyj[46][2],"_|    _| ");
    strcpy(nancyj[46][3],"_|    _| ");
    strcpy(nancyj[46][4],"_|    _| ");
    strcpy(nancyj[46][5],"  _|_|   ");
    strcpy(nancyj[46][6],"         ");
    strcpy(nancyj[46][7],"         ");
    strcpy(nancyj[47][0],"           ");
    strcpy(nancyj[47][1],"_|      _| ");
    strcpy(nancyj[47][2],"_|      _| ");
    strcpy(nancyj[47][3],"_|      _| ");
    strcpy(nancyj[47][4],"  _|  _|   ");
    strcpy(nancyj[47][5],"    _|     ");
    strcpy(nancyj[47][6],"           ");
    strcpy(nancyj[47][7],"           ");
    strcpy(nancyj[48][0],"               ");
    strcpy(nancyj[48][1],"_|          _| ");
    strcpy(nancyj[48][2],"_|          _| ");
    strcpy(nancyj[48][3],"_|    _|    _| ");
    strcpy(nancyj[48][4],"  _|  _|  _|   ");
    strcpy(nancyj[48][5],"    _|  _|     ");
    strcpy(nancyj[48][6],"               ");
    strcpy(nancyj[48][7],"               ");
    strcpy(nancyj[49][0],"           ");
    strcpy(nancyj[49][1],"_|      _| ");
    strcpy(nancyj[49][2],"  _|  _|   ");
    strcpy(nancyj[49][3],"    _|     ");
    strcpy(nancyj[49][4],"  _|  _|   ");
    strcpy(nancyj[49][5],"_|      _| ");
    strcpy(nancyj[49][6],"           ");
    strcpy(nancyj[49][7],"           ");
    strcpy(nancyj[50][0],"           ");
    strcpy(nancyj[50][1],"_|      _| ");
    strcpy(nancyj[50][2],"  _|  _|   ");
    strcpy(nancyj[50][3],"    _|     ");
    strcpy(nancyj[50][4],"    _|     ");
    strcpy(nancyj[50][5],"    _|     ");
    strcpy(nancyj[50][6],"           ");
    strcpy(nancyj[50][7],"           ");
    strcpy(nancyj[51][0],"           ");
    strcpy(nancyj[51][1],"_|_|_|_|_| ");
    strcpy(nancyj[51][2],"      _|   ");
    strcpy(nancyj[51][3],"    _|     ");
    strcpy(nancyj[51][4],"  _|       ");
    strcpy(nancyj[51][5],"_|_|_|_|_| ");
    strcpy(nancyj[51][6],"           ");
    strcpy(nancyj[51][7],"           ");
    strcpy(nancyj[52][0],"       ");
    strcpy(nancyj[52][1],"  _|   ");
    strcpy(nancyj[52][2],"_|  _| ");
    strcpy(nancyj[52][3],"_|  _| ");
    strcpy(nancyj[52][4],"_|  _| ");
    strcpy(nancyj[52][5],"  _|   ");
    strcpy(nancyj[52][6],"       ");
    strcpy(nancyj[52][7],"       ");
    strcpy(nancyj[53][0],"     ");
    strcpy(nancyj[53][1],"  _| ");
    strcpy(nancyj[53][2],"_|_| ");
    strcpy(nancyj[53][3],"  _| ");
    strcpy(nancyj[53][4],"  _| ");
    strcpy(nancyj[53][5],"  _| ");
    strcpy(nancyj[53][6],"     ");
    strcpy(nancyj[53][7],"     ");
    strcpy(nancyj[54][0],"         ");
    strcpy(nancyj[54][1],"  _|_|   ");
    strcpy(nancyj[54][2],"_|    _| ");
    strcpy(nancyj[54][3],"    _|   ");
    strcpy(nancyj[54][4],"  _|     ");
    strcpy(nancyj[54][5],"_|_|_|_| ");
    strcpy(nancyj[54][6],"         ");
    strcpy(nancyj[54][7],"         ");
    strcpy(nancyj[55][0],"         ");
    strcpy(nancyj[55][1],"_|_|_|   ");
    strcpy(nancyj[55][2],"      _| ");
    strcpy(nancyj[55][3],"  _|_|   ");
    strcpy(nancyj[55][4],"      _| ");
    strcpy(nancyj[55][5],"_|_|_|   ");
    strcpy(nancyj[55][6],"         ");
    strcpy(nancyj[55][7],"         ");
    strcpy(nancyj[56][0],"         ");
    strcpy(nancyj[56][1],"_|  _|   ");
    strcpy(nancyj[56][2],"_|  _|   ");
    strcpy(nancyj[56][3],"_|_|_|_| ");
    strcpy(nancyj[56][4],"    _|   ");
    strcpy(nancyj[56][5],"    _|   ");
    strcpy(nancyj[56][6],"         ");
    strcpy(nancyj[56][7],"         ");
    strcpy(nancyj[57][0],"         ");
    strcpy(nancyj[57][1],"_|_|_|_| ");
    strcpy(nancyj[57][2],"_|       ");
    strcpy(nancyj[57][3],"_|_|_|   ");
    strcpy(nancyj[57][4],"      _| ");
    strcpy(nancyj[57][5],"_|_|_|   ");
    strcpy(nancyj[57][6],"         ");
    strcpy(nancyj[57][7],"         ");
    strcpy(nancyj[58][0],"         ");
    strcpy(nancyj[58][1],"  _|_|_| ");
    strcpy(nancyj[58][2],"_|       ");
    strcpy(nancyj[58][3],"_|_|_|   ");
    strcpy(nancyj[58][4],"_|    _| ");
    strcpy(nancyj[58][5],"  _|_|   ");
    strcpy(nancyj[58][6],"         ");
    strcpy(nancyj[58][7],"         ");
    strcpy(nancyj[59][0],"           ");
    strcpy(nancyj[59][1],"_|_|_|_|_| ");
    strcpy(nancyj[59][2],"        _| ");
    strcpy(nancyj[59][3],"      _|   ");
    strcpy(nancyj[59][4],"    _|     ");
    strcpy(nancyj[59][5],"  _|       ");
    strcpy(nancyj[59][6],"           ");
    strcpy(nancyj[59][7],"           ");
    strcpy(nancyj[60][0],"         ");
    strcpy(nancyj[60][1],"  _|_|   ");
    strcpy(nancyj[60][2],"_|    _| ");
    strcpy(nancyj[60][3],"  _|_|   ");
    strcpy(nancyj[60][4],"_|    _| ");
    strcpy(nancyj[60][5],"  _|_|   ");
    strcpy(nancyj[60][6],"         ");
    strcpy(nancyj[60][7],"         ");
    strcpy(nancyj[61][0],"         ");
    strcpy(nancyj[61][1],"  _|_|   ");
    strcpy(nancyj[61][2],"_|    _| ");
    strcpy(nancyj[61][3],"  _|_|_| ");
    strcpy(nancyj[61][4],"      _| ");
    strcpy(nancyj[61][5],"_|_|_|   ");
    strcpy(nancyj[61][6],"         ");
    strcpy(nancyj[61][7],"         ");
    strcpy(nancyj[62][0],"       ");
    strcpy(nancyj[62][1],"       ");
    strcpy(nancyj[62][2],"       ");
    strcpy(nancyj[62][3],"       ");
    strcpy(nancyj[62][4],"       ");
    strcpy(nancyj[62][5],"       ");
    strcpy(nancyj[62][6],"       ");
    strcpy(nancyj[62][7],"       ");
    fwrite(nancyj,sizeof(char),10080,p_file);
    fclose(p_file);
    return 0;
}
